//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zuwi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequiredWidgetKey
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public int Widgets_Id { get; set; }
    
        public virtual Widget Widget { get; set; }
    }
}
