//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zuwi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WidgetData
    {
        public int Sites_Id { get; set; }
        public int Widgets_Id { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public int Id { get; set; }
    
        public virtual Site Site { get; set; }
        public virtual Widget Widget { get; set; }
    }
}
