//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WidgetCreator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZuwiDBEntities : DbContext
    {
        public ZuwiDBEntities()
            : base("name=ZuwiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RequiredWidgetKey> RequiredWidgetKeys { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<WidgetData> WidgetDatas { get; set; }
        public virtual DbSet<Widget> Widgets { get; set; }
    }
}
